language: node_js

node_js:
  - "4"
  - "5"
  - "6.2.2"

after_success:
  - npm run codecov

notifications:
  slack:
    secure: IlkNFtz4OjrGfmkFEjfVnAeFnoAs3ncgPuu3fEuzqRVaTWzl82NaxCD70PuQodGU5yAJQnhpFEhZcaV0oSl/lQllk9+08tgjgEULhQ3TiEt+GkaSZ5aiIORuQjeg1QhbZzjqB/BFWGq9QHcse/RgFtHLABgj3BndOZDDZTox262Efg9sC9SzUCUkUvDHs9Fx+6UqBfdp8RHlj/PMT/zImExUqsO4Atk7sFitpv92X0ezc2djeZpQxRYypPzaNmo8ZB8wB7Nw6iBAaSG3Ayij8i3zUQAQboSsQRSCik/KwNc/iYBmDXohdpB7ctO62cKC4rNJMxCvZsm3mSkFegc90Fi/0IMayZq2kjF4apKepeSIf1YZEoJHWz0305KrBwMrzsjeyrnA4KK2K5+vrp/NMiv0OvHSWriaaHJjhL/H3cn+uNh5SCBEQ1Shw0uGZK5UxYUdFgpabkUDaAJ6gGM1Y5hCA4lCbPRK7kD1LYEiVO/qzURHdt+VYji6/T7O85q0W1cod86rexVdw6RkoJ3B3mMGtyR60wk8MlZUyAXWhwFB8E0qo3ZF/6v3ZuonkSrDTxpMBVdDd6SuLEwcsHoqItIdfcDYKSljVNo8RE8ofOGjkIyfiiM82b+ECJHkVXG5Tp7VLVxqCX7nR69hMhMIidAs4d/+OnBnSLAKOSGTNMY=
